project:
  type: book
  output-dir: docs

book:
  title: "Cleaning transcriptomic datasets"
  author: "Carlos Ronchi"
  date: "2022.05.04"
  chapters:
    - index.qmd
    - tcga.qmd
    - metabric.qmd
    - scanb_new.qmd
    - ai.qmd
    - resources.qmd

bibliography: references.bib

execute:
  eval: false

format:
  html:
    theme: cosmo
    date-modified: last-modified
  pdf:
    documentclass: scrreprt



